apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world.fullname" . }}-svc
  labels:
    app: hello-world-argocd
  {{- include "hello-world.labels" . | nindent 4 }}
  annotations:
    oci.oraclecloud.com/load-balancer-type: lb
    service.beta.kubernetes.io/oci-load-balancer-shape: flexible
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
spec:
  type: {{ .Values.svc.type }}
  selector:
    app: hello-world-argocd
    {{- include "hello-world.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.svc.ports | toYaml | nindent 2 }}