apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
  labels:
    app: hello-world-argocd
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: LoadBalancer
#   type: NodePort
  selector:
    app: hello-world-argocd
  ports:
    - protocol: TCP
      port: 80
      name: http-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  labels:
      app: hello-world-argocd
spec:
  selector:
      matchLabels:
        app: hello-world-argocd
  replicas: 5
  template:
    metadata:
      labels:
        app: hello-world-argocd
    spec:
      containers:
      - name: hello-world
        image: quay.io/nearyd/hello-world-argocd:5.0
        ports:
        - containerPort: 80
          name: http-web

